### PR TITLE
various notes books for practising

### PR DESCRIPTION
**Pull request by sgathai**

### CODE REVIEW

**Comment by Cheffrey2000** [comment]
This is student work and will not be merged. Closing the PR

**Comment by sgathai** [comment]
please shed more light

**Comment by Cheffrey2000** [comment]
You created a pull request for your work to be merged into the flatiron school curriculum. Student work does not get merged into curriculum, so the pull request was closed. If this was an issue with the curriculum, please create an issue from the menu at the top.

**Comment by sgathai** [comment]
Hello ,

Thanks for this it was by mistake am really sorry for this 
Hopes is deactivated and no cause of alarm /confusion 

I need to train myself more on working with Git

**Comment by sgathai** [comment]
Are other persons able to view what i was doing ?

**Pull request closed without merging**
